[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-dev-tasks"
version = "0.1.0"
description = "AI Development Tasks Ecosystem"
requires-python = ">=3.12"


[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = ["venv", "600_archives", "docs/legacy", "**/__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]        # Line too long - handled by black

[tool.pytest.ini_options]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "e2e: End-to-end tests",
    "smoke: Smoke tests",
    "tier1: Tier 1 critical tests",
    "tier2: Tier 2 high priority tests",
    "tier3: Tier 3 supporting tests",
    "slow: Slow running tests",
    "fast: Fast running tests",
    "deprecated: Deprecated tests (do not run)",
]
testpaths = ["tests", "dspy-rag-system/tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
# Explicitly exclude archived tests
norecursedirs = ["600_archives", "venv", "docs/legacy", "__pycache__"]

[tool.pyright]
include = ["scripts", "tests", "dspy-rag-system"]
exclude = [
    "venv",
    "600_archives",
    "docs/legacy",
    "**/__pycache__",
    "scripts/eval",
]
pythonVersion = "3.12"
pythonPlatform = "Darwin"
extraPaths = ["scripts"]
reportMissingTypeStubs = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportOptionalMemberAccess = "none"
reportMissingImports = "none"
reportAssignmentType = "none"
reportPossiblyUnboundVariable = "none"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
tag_format = "v$version"
update_changelog_on_bump = true
allow_unconventional_commits = false

[tool.commitizen.customize]
allowed_types = ["feat", "fix", "refactor", "docs", "chore", "ci", "test"]
message_template = "{type}{scope}: {subject}\n\n{body}\n\n{footer}"
