[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-dev-tasks"
version = "0.1.0"
description = "AI Development Tasks Ecosystem"
requires-python = ">=3.8"

[tool.pyright]
pythonVersion = "3.8"
pythonPlatform = "Darwin"
venvPath = "."
venv = "venv"
extraPaths = ["venv/lib/python3.*/site-packages"]

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.ruff]
line-length = 120
target-version = "py39"
exclude = ["venv", "600_archives", "docs/legacy", "**/__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
