# Test suite budgets to prevent bloat
# These limits enforce discipline and prevent test suite explosion

suite_max_tests: 2500
new_tests_added_max: 30

folders:
  - path: tests/retriever
    max: 400
  - path: tests/reader
    max: 300
  - path: tests/evals
    max: 500
  - path: tests/legacy
    max: 999999 # exempt, but still counted
  - path: tests/integration
    max: 200
  - path: tests/unit
    max: 800
