default:
  w_path: 2.0
  w_short: 1.8
  w_title: 1.4
  w_bm25: 1.0
  w_vec: 1.1
  adjacency_db: 0
  per_file_cap: 4
  # Reranker configuration
  reranker_enabled: false
  reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  reranker_input_topk: 50
  reranker_keep: 12
  reranker_batch: 8
tags:
  db_workflows:
    w_path: 2.2
    w_short: 2.0
    w_title: 1.6
    w_bm25: 1.1
    w_vec: 1.4
  ops_health:
    w_path: 2.25
    w_short: 2.0
    w_title: 1.65
    w_bm25: 1.0
    w_vec: 1.2
  meta_ops:
    w_path: 2.15
    w_short: 1.9
    w_title: 1.65
    w_bm25: 1.0
    w_vec: 1.2
  rag_qa_single:
    w_path: 2.0
    w_short: 1.8
    w_title: 1.4
    w_bm25: 1.0
    w_vec: 1.2
