---
default:
  shortlist: 60 # retrieve this many, then MMR+cap
  topk: 25 # final K after rerank/cap
  # Reranker limits
  rerank_input_topk: 50 # candidates to send to reranker
  rerank_keep: 12 # final results after reranking

tags:
  db_workflows: { shortlist: 60, topk: 20 }
  ops_health: { shortlist: 60, topk: 22 }
  meta_ops: { shortlist: 60, topk: 22 }
  rag_qa_single: { shortlist: 60, topk: 25 }

answerability_thresholds:
  rag_qa_single: 0.10
  meta_ops: 0.10
  ops_health: 0.10
