[tool.black]
line-length = 120
target-version = ["py39"]

[tool.ruff]
line-length = 120
target-version = "py39"
exclude = [
  "venv",
  "600_archives",
  "docs/legacy",
  "**/__pycache__"
]

[tool.ruff.lint]
select = ["E", "F", "I"]
