name: "deterministic_evaluation Configuration"
description: "Configuration for deterministic_evaluation evaluation"
version: "1.0.0"
created_at: "2025-09-09T14:53:00Z"
tags: ["evaluation", "config"]
status: "active"
