---
default:
  shortlist: 60 # retrieve this many, then MMR+cap
  topk: 25 # final K after rerank/cap

tags:
  db_workflows: { shortlist: 60, topk: 25 }
  ops_health: { shortlist: 60, topk: 25 }
  meta_ops: { shortlist: 60, topk: 25 }
  rag_qa_single: { shortlist: 60, topk: 25 }
