# Test environment configuration
# Optimized for fast, deterministic testing

env: test

# Test database settings
db:
  dsn: "postgresql://danieljacobs@localhost:5432/ai_agency_test?sslmode=disable"
  pool_size: 2 # Minimal pool for tests
  timeout_ms: 2000 # Faster timeouts for tests

# Test RAG settings
rag:
  fast_path_enabled: true
  prefetch_workers: 1 # Single worker for tests
  chunk_size: 200 # Smaller chunks for faster tests
  topk: 5 # Fewer results for faster tests

# Test evaluation settings
eval:
  use_bedrock: false # Use mock models in tests
  bypass_cli: true
  lessons_mode: "disabled"
  disable_cache: true # Disable caching in tests

# Test observability
obs:
  log_level: "WARNING" # Reduce log noise in tests
  metrics_enabled: false

# Test performance settings
performance:
  max_memory_usage_mb: 2048 # Lower memory for tests
  max_concurrent_requests: 2
  test_timeout: 10 # Shorter test timeout

# Test memory settings
memory:
  ltst_enabled: false # Disable memory systems in tests
  cursor_enabled: false
  go_cli_enabled: false
  prime_enabled: false

# Test development settings
dev:
  environment: "test"
  debug_mode: false
  hot_reload: false
  test_parallel: true
  test_workers: 2 # Fewer workers for tests
  enable_profiling: false
  enable_debugging: false
  watch_files: false
