# Type stubs for common.db_dsn module
from typing import Optional

def _parse(dsn: str) -> dict[str, str | int]: ...
def resolve_dsn(strict: bool = True, emit_warning: bool = True) -> str | None: ...
