# Composite action: Standard Python 3.12 + uv environment
name: Setup Python + uv (3.12)
description: Install Python and uv, then sync project dependencies via uv
inputs:
  python-version:
    description: Python version to install
    required: false
    default: '3.12'
  uv-version:
    description: uv version to install
    required: false
    default: 'latest'
  sync-flags:
    description: Flags to pass to `uv sync`
    required: false
    default: '--all-extras --dev'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv-version }}
    - name: Sync deps (uv)
      shell: bash
      run: |
        uv --version
        uv sync ${{ inputs.sync-flags }}
