---
name: Nightly Test Signal

on:
  schedule:
    - cron: "20 5 * * *"

jobs:
  signal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist pytest-randomly \
            coverage radon datasketch

      - name: Coverage with per-test contexts
        run: |
          mkdir -p metrics
          coverage erase
          pytest -n auto --cov=src --cov=dspy-rag-system/src \
            --cov-branch --cov-context=test -q || true
          coverage combine
          coverage json -o metrics/coverage.json

      - name: Durations
        run: |
          pytest --durations=1000 -q > metrics/durations.txt || true

      - name: JUnit (latest)
        run: |
          pytest -q --junitxml=metrics/junit_latest.xml || true

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Churn
        run: |
          git log --pretty=format: --name-only | \
            rg -N '^(src|dspy-rag-system/src|configs)/' | \
            sort | uniq -c > metrics/churn.txt

      - name: Complexity
        run: |
          radon cc -s -j src dspy-rag-system/src > metrics/complexity.json

      - name: Build signal report
        run: |
          python scripts/test_signal_report.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-signal
          path: metrics/tests_signal.csv
