name: Nightly Property Tests

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  property-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Budget guard
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      
    - name: Install dependencies
      run: |
        uv sync --dev
        uv add hypothesis  # Add Hypothesis for property tests
        
    - name: Run property tests
      run: |
        # Set Hypothesis profile to nightly for more thorough testing
        export HYPOTHESIS_PROFILE=nightly
        uv run pytest tests/property/ -m prop --maxfail=1 -q --tb=short
        
    - name: Upload edge cases
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: hypothesis-edge-cases
        path: |
          tests/data/edge_cases.jsonl
          .hypothesis/examples/
        retention-days: 30
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: property-test-results
        path: |
          .hypothesis/
        retention-days: 7
