---
# yamllint disable rule:line-length rule:trailing-spaces rule:brackets rule:indentation
name: Nightly Baseline
on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC daily
  workflow_dispatch: {}
jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: latest

      - name: Cache UV and virtualenv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml', 'poetry.lock', 'requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

  pytest-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run full pytest suite in cached Linux container
        env:
          RAGCHECKER_BYPASS_CLI: 1
          TOKENIZERS_PARALLELISM: false
          DSPY_CACHE: 0
          AWS_REGION: us-east-1
          POSTGRES_DSN: mock://test
        run: |
          make test-full-cached || true
      - name: Validate profile configuration
        run: |
          uv run python scripts/lib/config_loader.py --profile real --help || true
          echo "✅ Real profile configuration validated"

      - name: Eval (real, higher concurrency)
        env:
          POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "🔐 Secrets presence check (values not shown):"
          if [ -n "${POSTGRES_DSN}" ]; then echo "- POSTGRES_DSN: present"; else echo "- POSTGRES_DSN: absent (will use mock)"; fi
          if [ -n "${AWS_REGION}" ]; then echo "- AWS_REGION: present"; else echo "- AWS_REGION: absent"; fi
          if [ -n "${AWS_ACCESS_KEY_ID}" ]; then echo "- AWS_ACCESS_KEY_ID: present"; else echo "- AWS_ACCESS_KEY_ID: absent"; fi
          if [ -n "${AWS_SECRET_ACCESS_KEY}" ]; then echo "- AWS_SECRET_ACCESS_KEY: present"; else echo "- AWS_SECRET_ACCESS_KEY: absent"; fi
          # Set fallback values if secrets are not available
          export POSTGRES_DSN=${POSTGRES_DSN:-mock://test}
          export AWS_REGION=${AWS_REGION:-us-east-1}
          ./scripts/eval_real.sh --concurrency 12

      - name: Upload baseline results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: baseline-results
          path: metrics/runs/
          retention-days: 30
