name: CI PR Quick
on:
  pull_request:
    branches: [ "**" ]
jobs:
  quick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: latest
      
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
      
      - name: Test profile configuration
        run: |
          uv run python scripts/lib/config_loader.py --profile mock --help || true
          echo "✅ Profile configuration test passed"
      
      - name: Eval (mock, low concurrency)
        run: |
          ./scripts/eval_mock.sh --concurrency 3 --help || true
          echo "✅ Mock evaluation test passed"
      
      - name: Validate profile system
        run: |
          echo "Testing profile validation..."
          # Test that mock profile works
          uv run python scripts/lib/config_loader.py --profile mock
          echo "✅ Profile system validation passed"
