name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Validate Commit Messages / PR Title
        run: |
          BASE_REF="${{ github.event.pull_request.base.sha }}"
          HEAD_REF="${{ github.event.pull_request.head.sha }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          if [ -n "${{ github.event.pull_request.merge_commit_sha }}" ]; then
            echo "Squash merge detected; validating PR title..."
            if ! uv run cz check --message "$PR_TITLE" --allowed-prefixes "merge:" "Merge:" "WIP:" "wip:"; then
              echo "⚠️  Warning: PR title doesn't follow conventional commit format"
              echo "✅ Allowing merge to proceed (non-blocking warning)"
            fi
          else
            echo "Validating commits in range $BASE_REF..$HEAD_REF"
            if ! uv run cz check --rev-range "$BASE_REF..$HEAD_REF" --allowed-prefixes "merge:" "Merge:" "WIP:" "wip:"; then
              echo "⚠️  Warning: Some commits don't follow conventional commit format"
              echo "✅ Allowing merge to proceed (non-blocking warning)"
            fi
          fi
