name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Commitizen
        run: pip install commitizen
      - name: Check commit messages in PR range
        run: |
          git fetch --depth=2 origin ${{ github.base_ref }}
          cz check --rev-range origin/${{ github.base_ref }}..
