name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Validate Commit Messages / PR Title
        run: |
          BASE_REF="${{ github.event.pull_request.base.sha }}"
          HEAD_REF="${{ github.event.pull_request.head.sha }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          if [ -n "${{ github.event.pull_request.merge_commit_sha }}" ]; then
            echo "Squash merge detected; validating PR title..."
            cz check --message "$PR_TITLE"
          else
            echo "Validating commits in range $BASE_REF..$HEAD_REF"
            cz check --rev-range "$BASE_REF..$HEAD_REF"
          fi
