name: Dry-Run CI (PR Signal)

on:
  pull_request:

jobs:
  checks:
    name: ruff + pyright + pytest (non-blocking)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (uv)
        run: |
          uv sync --all-extras --dev

      - name: Ruff
        run: echo "⚠️ Ruff checking temporarily disabled for database migration branch"

      - name: Pyright
        run: uv run pyright

      - name: Pytest
        run: uv run pytest -q --import-mode=importlib --ignore=600_archives --ignore=docs/legacy --ignore=600_archives/legacy-tests
