name: Dry-Run CI (PR Signal)

on:
  pull_request:

jobs:
  checks:
    name: ruff + pyright + pytest (non-blocking)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r dspy-rag-system/requirements.txt || true
          pip install -r dashboard/requirements.txt || true
          pip install -r config/requirements-conflict-detection.txt || true
          pip install ruff pyright pytest

      - name: Ruff
        run: ruff check .

      - name: Pyright
        run: pyright

      - name: Pytest
        run: pytest -q --import-mode=importlib
