name: Evals Docs
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jinja2 typer
      - name: Generate evaluation docs
        run: python -m evals_300.tools.gen
      - name: Check for changes
        run: git diff --exit-code -- evals_300/_generated
