name: Nightly Property Tests

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:
  property-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Fallback to uv if present
          if [ -f requirements-uv.txt ]; then pip install -r requirements-uv.txt || true; fi

      - name: Run property tests
        run: |
          pytest -q tests/property || true

      - name: Upload edge cases artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edge-cases-jsonl
          path: tests/data/edge_cases.jsonl
          if-no-files-found: warn

