name: Reader Gate CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  reader-gate:
    runs-on: ubuntu-latest
    env:
      HF_HOME: /tmp/hf
      SENTENCE_TRANSFORMERS_HOME: /tmp/hf
      TORCH_HOME: /tmp/hf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Setup UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Cache UV and virtualenv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml', 'poetry.lock', 'requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      - name: Cache HuggingFace models
        uses: actions/cache@v4
        with:
          path: /tmp/hf
          key: ${{ runner.os }}-hf-${{ hashFiles('**/pyproject.toml', '**/uv.lock', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-hf-
      - name: Install dependencies (uv)
        run: |
          uv sync
      - name: Run reader gate (v1)
        env:
          GOLD_FILE: "evals/gold/v1/gold_cases.jsonl"
          READER_CMD: "uv run python scripts/run_extractive_reader.py"
          READER_MIN_F1_MICRO: "0.35"
          READER_MIN_F1_TAG: "0.25"
          MAX_READER_REG_DROP: "0.05"
          PGVECTOR_OPS: "cosine"
          RETRIEVER_WEIGHTS_FILE: "configs/retriever_weights.yaml"
          RETRIEVER_LIMITS_FILE: "configs/retriever_limits.yaml"
          PER_FILE_CAP: "5"
          MMR_ALPHA: "0.85"
          READER_COMPACT: "1"
        run: uv run -- python scripts/ci_gate_reader.py

  update-reader-baseline:
    needs: reader-gate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update reader baseline
        run: |
          cp -f evals/latest_reader_metrics.json evals/baseline_reader_metrics.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add evals/baseline_reader_metrics.json
          git commit -m "CI: update baseline reader metrics [skip ci]" || echo "No changes"
          git push
