name: Schemas and Roundtrip Tests

on:
  push:
    branches: [ main, test-signal-implementation ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          pipx install uv

      - name: Sync deps
        run: |
          uv sync --all-extras --dev

      - name: Export schemas
        run: |
          uv run python scripts/export_schemas.py

      - name: Run quick gate tests
        env:
          RAGCHECKER_BYPASS_CLI: 1
          TOKENIZERS_PARALLELISM: false
          DSPY_CACHE: 0
          AWS_REGION: us-east-1
          POSTGRES_DSN: mock://test
        run: |
          make test-fast
