name: Shadow Flip to FAIL (PR H)

on:
  workflow_dispatch:
    inputs:
      force_flip:
        description: 'Force flip even if preconditions not met'
        required: false
        default: false
        type: boolean

jobs:
  check-preconditions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set validator environment (Shadow FAIL)
        run: |
          echo "VALIDATOR_REQUIRE_MULTI_REP=1" >> $GITHUB_ENV
          echo "VALIDATOR_REQUIRE_XREF=1" >> $GITHUB_ENV
          echo "VALIDATOR_STRICT_STALE_XREF=0" >> $GITHUB_ENV
          echo "VALIDATOR_CHECK_MODE=all" >> $GITHUB_ENV
          echo "VALIDATOR_CI_MODE=1" >> $GITHUB_ENV
          echo "VALIDATOR_ARCHIVE_FAIL=0" >> $GITHUB_ENV
          echo "VALIDATOR_SHADOW_FAIL=1" >> $GITHUB_ENV
          echo "VALIDATOR_README_FAIL=0" >> $GITHUB_ENV
          echo "VALIDATOR_MULTIREP_FAIL=0" >> $GITHUB_ENV

      - name: Run validator with Shadow FAIL
        run: |
          python3 scripts/doc_coherence_validator.py --ci --json > validator_report_shadow_fail.json
          echo "Validator with Shadow FAIL completed"

      - name: Check preconditions
        id: check_preconditions
        env:
          INPUT_FORCE_FLIP: ${{ github.event.inputs.force_flip }}
        run: |
          python3 - <<'PY'
          import json, subprocess, os

          # Load current report
          with open('validator_report_shadow_fail.json') as f:
              report = json.load(f)

          # Check shadow violations
          shadow_violations = report.get('impacted_files', {}).get('shadow_fork', [])
          shadow_count = len(shadow_violations)

          # Load counters
          def get_counters():
              try:
                  result = subprocess.run(["git", "show", "bot/validator-state:data/validator_counters.json"],
                                        capture_output=True, text=True, check=False)
                  if result.returncode == 0:
                      return json.loads(result.stdout)
              except Exception:
                  pass
              return {"shadow_fork": 0}

          counters = get_counters()
          shadow_clean_days = counters.get("shadow_fork", 0)

          print("## Shadow Flip Preconditions Check")
          print(f"- Shadow violations: {shadow_count}")
          print(f"- Shadow clean days: {shadow_clean_days}/7")
          force_flip = str(os.getenv('INPUT_FORCE_FLIP', 'false')).strip().lower() == 'true'
          print(f"- Force flip: {force_flip}")

          # Check preconditions
          preconditions_met = True
          issues = []

          if shadow_count > 0:
              preconditions_met = False
              issues.append(f"Shadow has {shadow_count} violations")

          if shadow_clean_days < 7:
              preconditions_met = False
              issues.append(f"Shadow clean days ({shadow_clean_days}) < 7")

          github_output = os.getenv('GITHUB_OUTPUT')
          if preconditions_met or force_flip:
              print("✅ Preconditions met or force flip enabled")
              if github_output:
                  with open(github_output, 'a') as gh_out:
                      gh_out.write('ready=true\n')
          else:
              print("❌ Preconditions not met:")
              for issue in issues:
                  print(f"  - {issue}")
              if github_output:
                  with open(github_output, 'a') as gh_out:
                      gh_out.write('ready=false\n')
              exit(1)
          PY

      - name: Generate flip PR
        if: steps.check_preconditions.outputs.ready == 'true'
        run: |
          python3 - <<'PY'
          import json, subprocess

          # Load report
          with open('validator_report_shadow_fail.json') as f:
              report = json.load(f)

          # Get counters
          def get_counters():
              try:
                  result = subprocess.run(["git", "show", "bot/validator-state:data/validator_counters.json"],
                                        capture_output=True, text=True, check=False)
                  if result.returncode == 0:
                      return json.loads(result.stdout)
              except Exception:
                  pass
              return {"shadow_fork": 0}

          counters = get_counters()
          shadow_days = counters.get('shadow_fork', 0)

          # Create simple PR template
          pr_content = f"# Shadow Flip to FAIL (PR H)\n\nShadow clean days: {shadow_days}/7\n\nSet VALIDATOR_SHADOW_FAIL=1"

          with open(".github/pull_request_template_shadow_flip.md", "w") as f:
              f.write(pr_content)

          print("✅ Shadow flip PR template created: .github/pull_request_template_shadow_flip.md")
          PY

      - name: Upload validator report
        uses: actions/upload-artifact@v4
        with:
          name: shadow-flip-report
          path: validator_report_shadow_fail.json

      - name: Job Summary
        run: |
          echo "## Shadow Flip Preconditions" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          python3 - <<'PY' >> $GITHUB_STEP_SUMMARY
          import json
          try:
              with open('validator_report_shadow_fail.json') as f:
                  report = json.load(f)

              shadow_violations = report.get('impacted_files', {}).get('shadow_fork', [])
              shadow_count = len(shadow_violations)

              print(f"- **Shadow Violations**: {shadow_count}")
              print(f"- **Status**: {'✅ READY' if shadow_count == 0 else '❌ NOT READY'}")

              if shadow_count == 0:
                  print("- **Action**: Ready for Shadow flip to FAIL")
              else:
                  print(f"- **Action**: Clean up {shadow_count} shadow violations first")

          except Exception as e:
              print(f"- **Error**: {e}")
          PY
